#!/usr/bin/env python
#-*- python -*-

################################################################################
# DIANE Project. http://cern.ch/diane
#
# $Id: acl,v 1.1 2008/02/14 13:58:06 moscicki Exp $
################################################################################

import os,sys

def usage():
    print ''' Change recursively AFS ACL rights on a given directory (default is .)
    acl protect [dir]  - write protected for all
    acl public [dir]   - make readible by all
    acl diane [dir]    - make writable by diane team
    '''
    sys.exit(2)

try:
    cmd = sys.argv[1]
except IndexError:
    usage()

dir = '.'
try:
    dir = sys.argv[2]
except IndexError:
    pass


cmds = { 'protect': ['find %s -type d -exec fs setacl -dir {} -clear -acl system:anyuser rl \;'],
         'public': ['find %s -type d -exec fs setacl -dir {} -acl system:anyuser rl \;'],
         'diane' : ['find %s -type d -exec fs setacl -dir {} -acl arda:diane rldiwk \;',
                    'find %s -type d -exec fs setacl -dir {} -acl arda:dianeadmin rldiwka \;']
         }

try:
    sc = cmds[cmd]
except KeyError:
    print 'unknown command',c
    usage()

print '"'+dir+'"','=>',cmd.upper()

for c in sc:
    c = c%dir
    print c
    os.system(c)
