#!/usr/bin/env bash
rm -f message.out
echo hello $* > message.out
echo 'reading in the cached input file and appending to message.out'
cat /tmp/diane-cache-wn/X >> message.out
echo "I said hello $* and saved it in message.out"
sleep 10
