"""
Utility module to set OMNIOrb
"""
import os
import os.path
import diane
from diane.diane_exceptions import DianeException
import diane.PACKAGE

def make_omniorb_config(runfile,role,dest):
   try:
      omniorb_config_type = runfile.get_value('omniorb_config_type',direct=False)
   except DianeException:
      omniorb_config_type = 'default'
   omniorb_config_name = '_'.join([omniorb_config_type,role])
   try:
      omniorb_config_string = runfile.get_value(omniorb_config_name,direct=False)
   except DianeException:
      default_config_file = '%s/etc/omniorb_config/%s.cfg' % (diane.PACKAGE.getReleaseDir(),omniorb_config_type)
      symbols = {}
      execfile(default_config_file,globals(),symbols)
      omniorb_config_string=symbols[omniorb_config_name]

   omniorb_config_string = """#######################################################################
# This file is automatically generated
# runfile: %s
# omniorb_config_type = %s
# role = %s
#######################################################################
"""%(runfile.filename,omniorb_config_type,role) + omniorb_config_string
   dest.write(omniorb_config_string)
   enable_GSI = 'gsi' in omniorb_config_type.lower()
   return enable_GSI

