Import('env')

env.Program(target = 'wordcount', source = Glob('wordcount.cpp'),
    LIBS = env['LIBS'] + ['saga_engine', 'saga_package_namespace', 'saga_package_job',
        'saga_package_filesystem', 'saga_package_advert', 'saga_package_stream',
        'saga_mapreduce_shared'])
