/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "Interface_constants.h"



const InterfaceConstants g_Interface_constants;

InterfaceConstants::InterfaceConstants() {
}



