/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef Interface_CONSTANTS_H
#define Interface_CONSTANTS_H

#include "Interface_types.h"



class InterfaceConstants {
 public:
  InterfaceConstants();

};

extern const InterfaceConstants g_Interface_constants;



#endif
