
#ifndef SAGA_ADAPTOR_DEFAULT_CONFIG_HPP
#define SAGA_ADAPTOR_DEFAULT_CONFIG_HPP

#include <saga/saga-defs.hpp>

#define SAGA_HAVE_SOCI              0
#define SAGA_HAVE_INTERNAL_SOCI     1
#define SAGA_HAVE_SOCI_SQLITE3      1
#define SAGA_HAVE_SOCI_POSTGRESQL   0
#define SAGA_HAVE_SOCI_MYSQL        0

#if SAGA_HAVE_SOCI || SAGA_HAVE_INTERNAL_SOCI
# if SAGA_HAVE_SOCI_SQLITE3
#  define SAGA_DEFAULT_ADAPTORS_USE_SQLITE3
# endif
# if SAGA_HAVE_SOCI_POSTGRESQL
#  define SAGA_DEFAULT_ADAPTORS_USE_POSTGRESQL
# endif
# if SAGA_HAVE_SOCI_MYSQL
#  define SAGA_DEFAULT_ADAPTORS_USE_MYSQL
# endif
#endif

#endif // SAGA_ADAPTOR_DEFAULT_CONFIG_HPP

