#-*-python-*-

import G4Analysis as application

from G4Analysis.Data import G4RunData

def run(input,config):
    input.data = G4RunData()
    input.data.runParameters.seed = 0
    input.data.runParameters.eventNumber = 400000
    input.data.eventChunk = 4000
    input.data.workerInit.outputfn = "brachytherapy.xml"
    input.data.workerInit.G4ApplicationName = 'G4Brachy'
    input.data.workerInit.initMacros = """
/control/verbose 1
/run/verbose 0
/event/verbose 0
/source/switch Iodium
/run/energy Iodium
/run/initialize
"""
