#!/bin/tcsh

# echo name: local.fork
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  ./log
# echo                                                                                
                                                                                      
# echo name: local.ssh                                                                
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  ./log
# echo                                                                                
                                                                                      
# echo name: local.condor                                                             
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  ./log
# echo                                                                                
                                                                                      
# echo name: local.condor-ssh                                                         
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  ./log 
# echo                                                                                
                                                                                      
# echo name: local.fork-ssh                                                           
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  ./log 
# echo                                                                                
                                                                                      
# echo name: local.fork-condor                                                      
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  ./log
# echo                                                                                
                                                                                      
# echo name: local.fork-condor-ssh                                                    
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  ./log 
# echo                                                                                
                                                                                      
# echo name: qb.ssh                                                                   
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.qb.ssh.txt                 >&  ./log
# echo                                                                                
                                                                                      
# echo name: ec2                                                                      
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.ec2.txt                    >&  ./log
# echo                                                                                
                                                                                      
# echo name: ec2.qb                                                                   
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.txt                 >&  ./log
# echo                                                                                
                                                                                      
echo name: ec2.qb.fork                                                                
# echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
# echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
# echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
# echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
# echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
# echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
# echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.fork.txt              >&  ./log
echo                                                                                  
                                                                                      
echo name: ec2.qb.condor                                                              
echo -n " 1: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 2: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 3: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 4: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 5: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 6: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 7: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 8: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n " 9: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo -n "10: " && time ./dax_parser dag.xml dax_scheduler.ec2.qb.condor.txt            >&  ./log 
echo

