#!/bin/tcsh

# echo local.fork
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.01.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.02.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.03.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.04.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.05.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.06.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.07.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.08.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.09.log
# time ./dax_parser dag.xml dax_scheduler.local.fork.txt             >&  local.fork.10.log
# echo

# echo local.ssh
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.01.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.02.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.03.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.04.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.05.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.06.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.07.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.08.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.09.log 
# time ./dax_parser dag.xml dax_scheduler.local.ssh.txt              >&  local.ssh.10.log 
# echo

# echo local.condor
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.01.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.02.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.03.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.04.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.05.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.06.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.07.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.08.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.09.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor.txt           >&  local.condor.10.log 
# echo

echo local.condor-ssh
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.01.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.02.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.03.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.04.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.05.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.06.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.07.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.08.log 
# time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.09.log 
time ./dax_parser dag.xml dax_scheduler.local.condor-ssh.txt       >&  local.condor-ssh.10.log 
echo

# echo local.fork-ssh
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.01.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.02.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.03.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.04.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.05.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.06.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.07.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.08.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.09.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-ssh.txt         >&  local.fork-ssh.10.log 
# echo

# echo local.fork-condor
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.01.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.02.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.03.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.04.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.05.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.06.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.07.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.08.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.09.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor.txt      >&  local.fork-condor.10.log 
# echo

echo local.fork-condor-ssh
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.01.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.02.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.03.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.04.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.05.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.06.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.07.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.08.log 
# time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.09.log 
time ./dax_parser dag.xml dax_scheduler.local.fork-condor-ssh.txt  >&  local.fork-condor-ssh.10.log 
echo

