#!/bin/bash

HOME=/home/latin
ATTR=$HOME/saga/condor_bin/condor_attr
JOB=$HOME/saga/condor_bin/condor_job

cat $ATTR > $JOB

while read l; do
    if [[ $l == ${l/#universe/} ]]; then
        echo $l >> $JOB
    fi
done

exec /usr/local/packages/condor-7.3.2/bin/condor_submit "$1" "$2" "$3" "$4" $JOB

#sleep 5

#rm -f $ATTR
#rm -f $JOB
