#  Copyright (c) 2005-2006 Andre Merzky (andre@merzky.net)
# 
#  Use, modification and distribution is subject to the Boost Software
#  License, Version 1.0. (See accompanying file LICENSE_1_0.txt or copy at
#  http://www.boost.org/LICENSE_1_0.txt)



# include the application helper make file
include $(SAGA_LOCATION)/share/saga/make/saga.application.mk

install::
	@$(ECHO) "     installing mapreduce samples"
	@$(MKDIR) -p            $(SAGA_LOCATION)/share/saga/mapreduce_samples/
	@$(CP)    *.xml file.txt $(SAGA_LOCATION)/share/saga/mapreduce_samples/

