/* ==========================================
   DIANE - Distributed Analysis Environment 
   Copyright (C) Jakub T. Moscicki, 2000-2003
   ------------------------------------------                                          
   See $DIANE_TOP/LICENSE for details.
   ========================================== 
*/

module DIANE_CORBA
{

  /**
   * ClientRunMaster is a client interface to the job master.
   *
   */
  interface ClientRunMaster
    {
      void setMonitoring(in boolean yes);
      boolean startJob(in Client, in DXPByteSeq job_data, in appinfo_t appname);
      boolean abortJob();
      boolean disconnect();
      boolean reconnect();
    };   
}
