# ifndef _DIANE__FILESERVER_IDL__
# define _DIANE__FILESERVER_IDL__ 1

/* ==========================================
   DIANE - Distributed Analysis Environment 
   Copyright (C) Jakub T. Moscicki, 2000-2003
   ------------------------------------------                                          
   See $DIANE_TOP/LICENSE for details.
   ========================================== 
*/

# include "types.idl"
# include "Peer.idl"

module DIANE_CORBA
{
    exception XFileTransferError
     {
	 string message;
	 //DXPByteSeq details;
     };

  /**
   * FileTransferServer is used to upload/download files.
   *
   */
    interface FileTransferServer : Peer
    {
	uuid_t start_file_download(in string filename, in uuid_t peer_uuid, in string transfer_opts) raises (XFileTransferError);
	uuid_t start_file_upload(in string filename, in uuid_t peer_uuid, in string transfer_opts) raises (XFileTransferError);

        void upload(in uuid_t session_id, in DXPByteSeq data, in short more) raises (XFileTransferError);
	DXPByteSeq download(in uuid_t session_id) raises (XFileTransferError);
    };


};

#endif
