#! /bin/csh
java NPB3_0_JAV.MG -serial CLASS=A
java NPB3_0_JAV.MG -np2 CLASS=A

java NPB3_0_JAV.CG -serial CLASS=A
java NPB3_0_JAV.CG -np2 CLASS=A

java NPB3_0_JAV.BT -serial CLASS=A
java NPB3_0_JAV.BT -np2 CLASS=A

java NPB3_0_JAV.SP -serial CLASS=A
java NPB3_0_JAV.SP -np2 CLASS=A

java NPB3_0_JAV.LU -serial CLASS=A
java NPB3_0_JAV.LU -np2 CLASS=A

java NPB3_0_JAV.FT -serial CLASS=A
java NPB3_0_JAV.FT -np2 CLASS=A

java NPB3_0_JAV.IS -serial CLASS=A
java NPB3_0_JAV.IS -np2 CLASS=A
