
#  Copyright (c) 2005-2006 Andre Merzky (andre@merzky.net)
# 
#  Distributed under the Boost Software License, Version 1.0. (See accompanying
#  file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

SAGA_SRC          = $(wildcard *.cpp)
SAGA_BIN          = thread_test

include $(SAGA_LOCATION)/share/saga/make/saga.application.mk

SAGA_CXXFLAGS    += -Wall # -ansi -std=c++98
SAGA_CPPINCS     += -I./

