// This comment will be included in the generated .h file
// You can include any additional declarations, includes, imports, etc.
// within [ ] sections. The brackets MUST appear at the start of a line
/* /usr/local/globus/share/schema/GridObjects/Monitorable.h
   Generated by wsdl2h 1.2.9l from /usr/local/globus/share/schema/GridObjects/Monitorable.wsdl and typemap.dat
   2008-02-22 03:59:19 GMT
   Copyright (C) 2001-2007 Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control schema namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt w

/******************************************************************************\
 *                                                                            *
 * http://monitorable.migol.ogsa.globus.org/Monitorable                       *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

migoldef = "http://monitorable.migol.ogsa.globus.org/Monitorable"
lifetime = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd"
xsd = "http://schemas.xmlsoap.org/ws/2004/03/addressing"
basefaults = "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd"

*/

//gsoap migoldef schema namespace:	http://monitorable.migol.ogsa.globus.org/Monitorable
//gsoap lifetime schema namespace:	http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd
//gsoap xsd   schema namespace:	http://schemas.xmlsoap.org/ws/2004/03/addressing
//gsoap basefaults schema namespace:	http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd
//gsoap migoldef schema form:	qualified
//gsoap lifetime schema elementForm:	qualified
//gsoap lifetime schema attributeForm:	unqualified
//gsoap xsd   schema elementForm:	qualified
//gsoap xsd   schema attributeForm:	unqualified
//gsoap basefaults schema elementForm:	qualified
//gsoap basefaults schema attributeForm:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/

class xsd__anyType { _XML __item; struct soap *soap; };

/// Primitive built-in type "xs:NCName"
typedef char* xsd__NCName;

/// Class wrapper for built-in type "xs:NCName" derived from xsd__anyType
class xsd__NCName_ : public xsd__anyType
{ public:
    xsd__NCName                          __item;                       
};

/// Class wrapper for built-in type "xs:QName" derived from xsd__anyType
class xsd__QName : public xsd__anyType
{ public:
    _QName                               __item;                       
};

/// Primitive built-in type "xs:anyURI"
typedef char* xsd__anyURI;

/// Class wrapper for built-in type "xs:anyURI" derived from xsd__anyType
class xsd__anyURI_ : public xsd__anyType
{ public:
    xsd__anyURI                          __item;                       
};

/// Class wrapper for built-in type "xs:boolean" derived from xsd__anyType
class xsd__boolean : public xsd__anyType
{ public:
    bool                                 __item;                       
};

/// Class wrapper for built-in type "xs:dateTime" derived from xsd__anyType
class xsd__dateTime : public xsd__anyType
{ public:
    time_t                               __item;                       
};

/// Primitive built-in type "xs:nonNegativeInteger"
typedef char* xsd__nonNegativeInteger;

/// Class wrapper for built-in type "xs:nonNegativeInteger" derived from xsd__anyType
class xsd__nonNegativeInteger_ : public xsd__anyType
{ public:
    xsd__nonNegativeInteger              __item;                       
};

/// Class wrapper for built-in type "xs:string" derived from xsd__anyType
class xsd__string : public xsd__anyType
{ public:
    char*                                __item;                       
};

/// Built-in attribute "xml:lang".
typedef char* _xml__lang;


/// Element "http://monitorable.migol.ogsa.globus.org/Monitorable":checkService.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://monitorable.migol.ogsa.globus.org/Monitorable":checkPoint.
/// Note: use wsdl2h option -g to generate this global element declaration.

//  Forward declaration of class lifetime__ResourceUnknownFaultType.
class lifetime__ResourceUnknownFaultType;

//  Forward declaration of class lifetime__ResourceNotDestroyedFaultType.
class lifetime__ResourceNotDestroyedFaultType;

//  Forward declaration of class lifetime__UnableToSetTerminationTimeFaultType.
class lifetime__UnableToSetTerminationTimeFaultType;

//  Forward declaration of class lifetime__TerminationTimeChangeRejectedFaultType.
class lifetime__TerminationTimeChangeRejectedFaultType;

//  Forward declaration of class _lifetime__ScheduledResourceTerminationRP.
class _lifetime__ScheduledResourceTerminationRP;

//  Forward declaration of class _lifetime__Destroy.
class _lifetime__Destroy;

//  Forward declaration of class _lifetime__DestroyResponse.
class _lifetime__DestroyResponse;

//  Forward declaration of class _lifetime__SetTerminationTime.
class _lifetime__SetTerminationTime;

//  Forward declaration of class _lifetime__SetTerminationTimeResponse.
class _lifetime__SetTerminationTimeResponse;

//  Forward declaration of class _lifetime__TerminationNotification.
class _lifetime__TerminationNotification;

//  Forward declaration of class xsd__EndpointReferenceType.
class xsd__EndpointReferenceType;

//  Forward declaration of class xsd__ReferencePropertiesType.
class xsd__ReferencePropertiesType;

//  Forward declaration of class xsd__ServiceNameType.
class xsd__ServiceNameType;

//  Forward declaration of class xsd__Relationship.
class xsd__Relationship;

//  Forward declaration of class xsd__ReplyAfterType.
class xsd__ReplyAfterType;

//  Forward declaration of class xsd__AttributedQName.
class xsd__AttributedQName;

//  Forward declaration of class xsd__AttributedURI.
class xsd__AttributedURI;

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":ReplyAfter.
/// Note: use wsdl2h option -g to generate this global element declaration.

//  Forward declaration of class basefaults__BaseFaultType.
class basefaults__BaseFaultType;

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":RelationshipTypeValues is a simpleType restriction of xs:QName.
/// Note: enum values are prefixed with 'xsd__RelationshipTypeValues' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum xsd__RelationshipTypeValues
{
	xsd__RelationshipTypeValues__xsd__Reply,	///< xs:QName value=""http://schemas.xmlsoap.org/ws/2004/03/addressing":Reply"
};

/// Class wrapper
class xsd__RelationshipTypeValues_ : public xsd__anyType
{ public:
    enum xsd__RelationshipTypeValues     __item;                       
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":FaultSubcodeValues is a simpleType restriction of xs:QName.
/// Note: enum values are prefixed with 'xsd__FaultSubcodeValues' to avoid name clashes, please use wsdl2h option -e to omit this prefix
enum xsd__FaultSubcodeValues
{
	xsd__FaultSubcodeValues__xsd__InvalidMessageInformationHeader,	///< xs:QName value=""http://schemas.xmlsoap.org/ws/2004/03/addressing":InvalidMessageInformationHeader"
	xsd__FaultSubcodeValues__xsd__MessageInformationHeaderRequired,	///< xs:QName value=""http://schemas.xmlsoap.org/ws/2004/03/addressing":MessageInformationHeaderRequired"
	xsd__FaultSubcodeValues__xsd__DestinationUnreachable,	///< xs:QName value=""http://schemas.xmlsoap.org/ws/2004/03/addressing":DestinationUnreachable"
	xsd__FaultSubcodeValues__xsd__ActionNotSupported,	///< xs:QName value=""http://schemas.xmlsoap.org/ws/2004/03/addressing":ActionNotSupported"
	xsd__FaultSubcodeValues__xsd__EndpointUnavailable,	///< xs:QName value=""http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointUnavailable"
};

/// Class wrapper
class xsd__FaultSubcodeValues_ : public xsd__anyType
{ public:
    enum xsd__FaultSubcodeValues         __item;                       
};


/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ScheduledResourceTerminationRP of complexType.

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ScheduledResourceTerminationRP is a complexType.
class _lifetime__ScheduledResourceTerminationRP
{ public:
/// Element reference "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":CurrentTime.
    time_t                               lifetime__CurrentTime          1;	///< Required element.
/// Element reference "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":TerminationTime.
    time_t                               lifetime__TerminationTime      1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":Destroy of complexType.

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":Destroy is a complexType.
class _lifetime__Destroy
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":DestroyResponse of complexType.

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":DestroyResponse is a complexType.
class _lifetime__DestroyResponse
{ public:
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":SetTerminationTime of complexType.

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":SetTerminationTime is a complexType.
class _lifetime__SetTerminationTime
{ public:
/// Element RequestedTerminationTime of type xs:dateTime.
    time_t*                              RequestedTerminationTime      ;	///< Nullable pointer.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":SetTerminationTimeResponse of complexType.

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":SetTerminationTimeResponse is a complexType.
class _lifetime__SetTerminationTimeResponse
{ public:
/// Element NewTerminationTime of type xs:dateTime.
    time_t*                              NewTerminationTime            ;	///< Nullable pointer.
/// Element CurrentTime of type xs:dateTime.
    time_t                               CurrentTime                    1;	///< Required element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};


/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":TerminationNotification of complexType.

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":TerminationNotification is a complexType.
class _lifetime__TerminationNotification
{ public:
/// Element TerminationTime of type xs:dateTime.
    time_t                               TerminationTime                1;	///< Required element.
/// Element TerminationReason of type xs:anyType.
    xsd__anyType*                        TerminationReason              0;	///< Optional element.
/// A handle to the soap struct that manages this instance (automatically set)
    struct soap                         *soap                          ;
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType is a complexType.
class xsd__EndpointReferenceType : public xsd__anyType
{ public:
/// Element Address of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":AttributedURI.
    xsd__AttributedURI*                  Address                        1;	///< Required element.
/// Element ReferenceProperties of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":ReferencePropertiesType.
    xsd__ReferencePropertiesType*        ReferenceProperties            0;	///< Optional element.
/// Element PortType of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":AttributedQName.
    xsd__AttributedQName*                PortType                       0;	///< Optional element.
/// Element ServiceName of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":ServiceNameType.
    xsd__ServiceNameType*                ServiceName                    0;	///< Optional element.
/// TODO: <any namespace="##other" minOccurs="0" maxOccurs="unbounded">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d for xsd__anyType DOM (soap_dom_element).
/// Size of the dynamic array of XML is 0..unbounded
    int                                  __size                        ;
    _XML                                *__any                         ;	///< Catch any element content in XML string.
/// <anyAttribute namespace="##other">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
///       Use wsdl2h option -d for xsd__anyAttribute DOM (soap_dom_attribute).
   @_XML                                 __anyAttribute                ;	///< A placeholder that has no effect: please see comment.
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":ReferencePropertiesType is a complexType.
class xsd__ReferencePropertiesType : public xsd__anyType
{ public:
/// TODO: <any minOccurs="0" maxOccurs="unbounded">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this element.
///       Use wsdl2h option -d for xsd__anyType DOM (soap_dom_element).
/// Size of the dynamic array of XML is 0..unbounded
    int                                  __size                        ;
    _XML                                *__any                         ;	///< Catch any element content in XML string.
};

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd":BaseFaultType is a complexType.
class basefaults__BaseFaultType : public xsd__anyType
{ public:
/// Element Timestamp of type xs:dateTime.
    time_t                               Timestamp                      1;	///< Required element.
/// Element Originator of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
    xsd__EndpointReferenceType*          Originator                     0;	///< Optional element.
    class _basefaults__BaseFaultType_ErrorCode
    {
/// Attribute dialect of type xs:anyURI.
   @xsd__anyURI                          dialect                        1;	///< Required attribute.
    }                                   *ErrorCode                      0;	///< Optional element.
/// Size of Description array is 0..unbounded
    int                                  __sizeDescription             ;
    class _basefaults__BaseFaultType_Description
    {
/// __item wraps 'xs:string' simpleContent.
    char*                                __item                        ;
/// Imported attribute reference xml:lang.
   @_xml__lang                           xml__lang                      0;	///< Optional attribute.
    }                                   *Description                    0;
/// Size of array of basefaults__BaseFaultType* is 0..unbounded
    int                                  __sizeFaultCause              ;
/// Pointer to array of length 0..unbounded
    basefaults__BaseFaultType*          *FaultCause                     0;
};

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ResourceUnknownFaultType is a complexType with complexContent extension of "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd":BaseFaultType.
class lifetime__ResourceUnknownFaultType : public basefaults__BaseFaultType
{ public:
/*  INHERITED FROM basefaults__BaseFaultType:
/// Element Timestamp of type xs:dateTime.
    time_t                               Timestamp                      1;	///< Required element.
/// Element Originator of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
    xsd__EndpointReferenceType*          Originator                     0;	///< Optional element.
    class _basefaults__ResourceUnknownFaultType_ErrorCode
    {
/// Attribute dialect of type xs:anyURI.
   @xsd__anyURI                          dialect                        1;	///< Required attribute.
    }                                   *ErrorCode                      0;	///< Optional element.
/// Size of Description array is 0..unbounded
    int                                  __sizeDescription             ;
    class _basefaults__ResourceUnknownFaultType_Description
    {
/// __item wraps 'xs:string' simpleContent.
    char*                                __item                        ;
/// Imported attribute reference xml:lang.
   @_xml__lang                           xml__lang                      0;	///< Optional attribute.
    }                                   *Description                    0;
/// Size of array of basefaults__BaseFaultType* is 0..unbounded
    int                                  __sizeFaultCause              ;
/// Pointer to array of length 0..unbounded
    basefaults__BaseFaultType*          *FaultCause                     0;
    END OF INHERITED */
};

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ResourceNotDestroyedFaultType is a complexType with complexContent extension of "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd":BaseFaultType.
class lifetime__ResourceNotDestroyedFaultType : public basefaults__BaseFaultType
{ public:
/*  INHERITED FROM basefaults__BaseFaultType:
/// Element Timestamp of type xs:dateTime.
    time_t                               Timestamp                      1;	///< Required element.
/// Element Originator of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
    xsd__EndpointReferenceType*          Originator                     0;	///< Optional element.
    class _basefaults__ResourceNotDestroyedFaultType_ErrorCode
    {
/// Attribute dialect of type xs:anyURI.
   @xsd__anyURI                          dialect                        1;	///< Required attribute.
    }                                   *ErrorCode                      0;	///< Optional element.
/// Size of Description array is 0..unbounded
    int                                  __sizeDescription             ;
    class _basefaults__ResourceNotDestroyedFaultType_Description
    {
/// __item wraps 'xs:string' simpleContent.
    char*                                __item                        ;
/// Imported attribute reference xml:lang.
   @_xml__lang                           xml__lang                      0;	///< Optional attribute.
    }                                   *Description                    0;
/// Size of array of basefaults__BaseFaultType* is 0..unbounded
    int                                  __sizeFaultCause              ;
/// Pointer to array of length 0..unbounded
    basefaults__BaseFaultType*          *FaultCause                     0;
    END OF INHERITED */
};

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":UnableToSetTerminationTimeFaultType is a complexType with complexContent extension of "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd":BaseFaultType.
class lifetime__UnableToSetTerminationTimeFaultType : public basefaults__BaseFaultType
{ public:
/*  INHERITED FROM basefaults__BaseFaultType:
/// Element Timestamp of type xs:dateTime.
    time_t                               Timestamp                      1;	///< Required element.
/// Element Originator of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
    xsd__EndpointReferenceType*          Originator                     0;	///< Optional element.
    class _basefaults__UnableToSetTerminationTimeFaultType_ErrorCode
    {
/// Attribute dialect of type xs:anyURI.
   @xsd__anyURI                          dialect                        1;	///< Required attribute.
    }                                   *ErrorCode                      0;	///< Optional element.
/// Size of Description array is 0..unbounded
    int                                  __sizeDescription             ;
    class _basefaults__UnableToSetTerminationTimeFaultType_Description
    {
/// __item wraps 'xs:string' simpleContent.
    char*                                __item                        ;
/// Imported attribute reference xml:lang.
   @_xml__lang                           xml__lang                      0;	///< Optional attribute.
    }                                   *Description                    0;
/// Size of array of basefaults__BaseFaultType* is 0..unbounded
    int                                  __sizeFaultCause              ;
/// Pointer to array of length 0..unbounded
    basefaults__BaseFaultType*          *FaultCause                     0;
    END OF INHERITED */
};

/// "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":TerminationTimeChangeRejectedFaultType is a complexType with complexContent extension of "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd":BaseFaultType.
class lifetime__TerminationTimeChangeRejectedFaultType : public basefaults__BaseFaultType
{ public:
/*  INHERITED FROM basefaults__BaseFaultType:
/// Element Timestamp of type xs:dateTime.
    time_t                               Timestamp                      1;	///< Required element.
/// Element Originator of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
    xsd__EndpointReferenceType*          Originator                     0;	///< Optional element.
    class _basefaults__TerminationTimeChangeRejectedFaultType_ErrorCode
    {
/// Attribute dialect of type xs:anyURI.
   @xsd__anyURI                          dialect                        1;	///< Required attribute.
    }                                   *ErrorCode                      0;	///< Optional element.
/// Size of Description array is 0..unbounded
    int                                  __sizeDescription             ;
    class _basefaults__TerminationTimeChangeRejectedFaultType_Description
    {
/// __item wraps 'xs:string' simpleContent.
    char*                                __item                        ;
/// Imported attribute reference xml:lang.
   @_xml__lang                           xml__lang                      0;	///< Optional attribute.
    }                                   *Description                    0;
/// Size of array of basefaults__BaseFaultType* is 0..unbounded
    int                                  __sizeFaultCause              ;
/// Pointer to array of length 0..unbounded
    basefaults__BaseFaultType*          *FaultCause                     0;
    END OF INHERITED */
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":ServiceNameType is a complexType with simpleContent.
class xsd__ServiceNameType : public xsd__anyType
{ public:
/// __item wraps 'xs:QName' simpleContent.
    _QName                               __item                        ;
/// Attribute PortName of type xs:NCName.
   @xsd__NCName                          PortName                       0;	///< Optional attribute.
/// <anyAttribute namespace="##other">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
///       Use wsdl2h option -d for xsd__anyAttribute DOM (soap_dom_attribute).
   @_XML                                 __anyAttribute                ;	///< A placeholder that has no effect: please see comment.
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":Relationship is a complexType with simpleContent.
class xsd__Relationship : public xsd__anyType
{ public:
/// __item wraps 'xs:anyURI' simpleContent.
    xsd__anyURI                          __item                        ;
/// Attribute RelationshipType of type xs:QName.
   @_QName                               RelationshipType               0;	///< Optional attribute.
/// <anyAttribute namespace="##other">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
///       Use wsdl2h option -d for xsd__anyAttribute DOM (soap_dom_attribute).
   @_XML                                 __anyAttribute                ;	///< A placeholder that has no effect: please see comment.
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":ReplyAfterType is a complexType with simpleContent.
class xsd__ReplyAfterType : public xsd__anyType
{ public:
/// __item wraps 'xs:nonNegativeInteger' simpleContent.
    xsd__nonNegativeInteger              __item                        ;
/// <anyAttribute namespace="##other">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
///       Use wsdl2h option -d for xsd__anyAttribute DOM (soap_dom_attribute).
   @_XML                                 __anyAttribute                ;	///< A placeholder that has no effect: please see comment.
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":AttributedQName is a complexType with simpleContent.
class xsd__AttributedQName : public xsd__anyType
{ public:
/// __item wraps 'xs:QName' simpleContent.
    _QName                               __item                        ;
/// <anyAttribute namespace="##other">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
///       Use wsdl2h option -d for xsd__anyAttribute DOM (soap_dom_attribute).
   @_XML                                 __anyAttribute                ;	///< A placeholder that has no effect: please see comment.
};

/// "http://schemas.xmlsoap.org/ws/2004/03/addressing":AttributedURI is a complexType with simpleContent.
class xsd__AttributedURI : public xsd__anyType
{ public:
/// __item wraps 'xs:anyURI' simpleContent.
    xsd__anyURI                          __item                        ;
/// <anyAttribute namespace="##other">
/// TODO: Schema extensibility is user-definable.
///       Consult the protocol documentation to change or insert declarations.
///       Use wsdl2h option -x to remove this attribute.
///       Use wsdl2h option -d for xsd__anyAttribute DOM (soap_dom_attribute).
   @_XML                                 __anyAttribute                ;	///< A placeholder that has no effect: please see comment.
};

/// Element "http://monitorable.migol.ogsa.globus.org/Monitorable":checkServiceResponse of type xs:boolean.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://monitorable.migol.ogsa.globus.org/Monitorable":checkPointResponse of type xs:boolean.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ResourceUnknownFault of type "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ResourceUnknownFaultType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ResourceNotDestroyedFault of type "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":ResourceNotDestroyedFaultType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":UnableToSetTerminationTimeFault of type "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":UnableToSetTerminationTimeFaultType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":TerminationTimeChangeRejectedFault of type "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":TerminationTimeChangeRejectedFaultType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":CurrentTime of type xs:dateTime.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-ResourceLifetime-1.2-draft-01.xsd":TerminationTime of type xs:dateTime.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReference of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":MessageID of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":AttributedURI.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":RelatesTo of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":Relationship.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":To of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":AttributedURI.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":Action of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":AttributedURI.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":From of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":ReplyTo of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Element "http://schemas.xmlsoap.org/ws/2004/03/addressing":FaultTo of type "http://schemas.xmlsoap.org/ws/2004/03/addressing":EndpointReferenceType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/// Attribute "http://schemas.xmlsoap.org/ws/2004/03/addressing":Action of simpleType xs:anyURI.
// '_xsd__Action' attribute definition intentionally left blank.

/// Element "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd":BaseFault of type "http://docs.oasis-open.org/wsrf/2004/06/wsrf-WS-BaseFaults-1.2-draft-01.xsd":BaseFaultType.
/// Note: use wsdl2h option -g to generate this global element declaration.

/* End of /usr/local/globus/share/schema/GridObjects/Monitorable.h */
