/* monitorServer.cpp
   Generated by gSOAP 2.7.9l from Monitorable_service.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/
#include "monitorH.h"

SOAP_SOURCE_STAMP("@(#) monitorServer.cpp ver 2.7.9l 2008-02-22 04:18:05 GMT")


SOAP_FMAC5 int SOAP_FMAC6 monitor_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif

	do
	{
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			soap->error = SOAP_EOF;
			return soap_send_fault(soap);
		}
#endif

		soap_begin(soap);

#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif

		if (soap_begin_recv(soap))
		{	if (soap->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(soap);
#else 
				return soap_send_fault(soap);
#endif
			}
			soap_closesock(soap);

			continue;
		}

		if (soap_envelope_begin_in(soap)
		 || soap_recv_header(soap)
		 || soap_body_begin_in(soap)
		 || monitor_serve_request(soap)
		 || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 monitor_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "migoldef:checkService"))
		return soap_serve___migol__checkService(soap);
	if (!soap_match_tag(soap, soap->tag, "migoldef:checkPoint"))
		return soap_serve___migol__checkPoint(soap);
	if (!soap_match_tag(soap, soap->tag, "lifetime:Destroy"))
		return soap_serve___migol__Destroy(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___migol__checkService(struct soap *soap)
{	struct __migol__checkService soap_tmp___migol__checkService;
	struct __migol__checkServiceResponse soap_tmp___migol__checkServiceResponse;
	soap_default___migol__checkServiceResponse(soap, &soap_tmp___migol__checkServiceResponse);
	soap_default___migol__checkService(soap, &soap_tmp___migol__checkService);
	soap->encodingStyle = NULL;
	if (!soap_get___migol__checkService(soap, &soap_tmp___migol__checkService, "-migol:checkService", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __migol__checkService(soap, soap_tmp___migol__checkService.migoldef__checkService, soap_tmp___migol__checkServiceResponse.migoldef__checkServiceResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize___migol__checkServiceResponse(soap, &soap_tmp___migol__checkServiceResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___migol__checkServiceResponse(soap, &soap_tmp___migol__checkServiceResponse, "-migol:checkServiceResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___migol__checkServiceResponse(soap, &soap_tmp___migol__checkServiceResponse, "-migol:checkServiceResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___migol__checkPoint(struct soap *soap)
{	struct __migol__checkPoint soap_tmp___migol__checkPoint;
	struct __migol__checkPointResponse soap_tmp___migol__checkPointResponse;
	soap_default___migol__checkPointResponse(soap, &soap_tmp___migol__checkPointResponse);
	soap_default___migol__checkPoint(soap, &soap_tmp___migol__checkPoint);
	soap->encodingStyle = NULL;
	if (!soap_get___migol__checkPoint(soap, &soap_tmp___migol__checkPoint, "-migol:checkPoint", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __migol__checkPoint(soap, soap_tmp___migol__checkPoint.migoldef__checkPoint, soap_tmp___migol__checkPointResponse.migoldef__checkPointResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize___migol__checkPointResponse(soap, &soap_tmp___migol__checkPointResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___migol__checkPointResponse(soap, &soap_tmp___migol__checkPointResponse, "-migol:checkPointResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___migol__checkPointResponse(soap, &soap_tmp___migol__checkPointResponse, "-migol:checkPointResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve___migol__Destroy(struct soap *soap)
{	struct __migol__Destroy soap_tmp___migol__Destroy;
	_lifetime__DestroyResponse lifetime__DestroyResponse;
	lifetime__DestroyResponse.soap_default(soap);
	soap_default___migol__Destroy(soap, &soap_tmp___migol__Destroy);
	soap->encodingStyle = NULL;
	if (!soap_get___migol__Destroy(soap, &soap_tmp___migol__Destroy, "-migol:Destroy", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = __migol__Destroy(soap, soap_tmp___migol__Destroy.lifetime__Destroy, &lifetime__DestroyResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	lifetime__DestroyResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || lifetime__DestroyResponse.soap_put(soap, "lifetime:DestroyResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || lifetime__DestroyResponse.soap_put(soap, "lifetime:DestroyResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

/* End of monitorServer.cpp */
