/* monitorH.h
   Generated by gSOAP 2.7.9l from Monitorable_service.h
   Copyright(C) 2000-2007, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef monitorH_H
#define monitorH_H
#include "monitorStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (2)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_time
#define SOAP_TYPE_time (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_time(struct soap*, time_t *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_time(struct soap*, const time_t *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_time(struct soap*, const char*, int, const time_t *, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_get_time(struct soap*, time_t *, const char*, const char*);
SOAP_FMAC3 time_t * SOAP_FMAC4 soap_in_time(struct soap*, const char*, time_t *, const char*);

#ifndef SOAP_TYPE_xsd__FaultSubcodeValues
#define SOAP_TYPE_xsd__FaultSubcodeValues (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__FaultSubcodeValues(struct soap*, enum xsd__FaultSubcodeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__FaultSubcodeValues(struct soap*, const enum xsd__FaultSubcodeValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__FaultSubcodeValues(struct soap*, const char*, int, const enum xsd__FaultSubcodeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__FaultSubcodeValues2s(struct soap*, enum xsd__FaultSubcodeValues);
SOAP_FMAC3 enum xsd__FaultSubcodeValues * SOAP_FMAC4 soap_get_xsd__FaultSubcodeValues(struct soap*, enum xsd__FaultSubcodeValues *, const char*, const char*);
SOAP_FMAC3 enum xsd__FaultSubcodeValues * SOAP_FMAC4 soap_in_xsd__FaultSubcodeValues(struct soap*, const char*, enum xsd__FaultSubcodeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__FaultSubcodeValues(struct soap*, const char*, enum xsd__FaultSubcodeValues *);

#ifndef SOAP_TYPE_xsd__RelationshipTypeValues
#define SOAP_TYPE_xsd__RelationshipTypeValues (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__RelationshipTypeValues(struct soap*, enum xsd__RelationshipTypeValues *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__RelationshipTypeValues(struct soap*, const enum xsd__RelationshipTypeValues *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__RelationshipTypeValues(struct soap*, const char*, int, const enum xsd__RelationshipTypeValues *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__RelationshipTypeValues2s(struct soap*, enum xsd__RelationshipTypeValues);
SOAP_FMAC3 enum xsd__RelationshipTypeValues * SOAP_FMAC4 soap_get_xsd__RelationshipTypeValues(struct soap*, enum xsd__RelationshipTypeValues *, const char*, const char*);
SOAP_FMAC3 enum xsd__RelationshipTypeValues * SOAP_FMAC4 soap_in_xsd__RelationshipTypeValues(struct soap*, const char*, enum xsd__RelationshipTypeValues *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__RelationshipTypeValues(struct soap*, const char*, enum xsd__RelationshipTypeValues *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE__basefaults__BaseFaultType_Description
#define SOAP_TYPE__basefaults__BaseFaultType_Description (54)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__basefaults__BaseFaultType_Description(struct soap*, const char*, int, const _basefaults__BaseFaultType_Description *, const char*);
SOAP_FMAC3 _basefaults__BaseFaultType_Description * SOAP_FMAC4 soap_get__basefaults__BaseFaultType_Description(struct soap*, _basefaults__BaseFaultType_Description *, const char*, const char*);
SOAP_FMAC3 _basefaults__BaseFaultType_Description * SOAP_FMAC4 soap_in__basefaults__BaseFaultType_Description(struct soap*, const char*, _basefaults__BaseFaultType_Description *, const char*);
SOAP_FMAC5 _basefaults__BaseFaultType_Description * SOAP_FMAC6 soap_new__basefaults__BaseFaultType_Description(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__basefaults__BaseFaultType_Description(struct soap*, _basefaults__BaseFaultType_Description*);
SOAP_FMAC3 _basefaults__BaseFaultType_Description * SOAP_FMAC4 soap_instantiate__basefaults__BaseFaultType_Description(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__basefaults__BaseFaultType_Description(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__basefaults__BaseFaultType_ErrorCode
#define SOAP_TYPE__basefaults__BaseFaultType_ErrorCode (52)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__basefaults__BaseFaultType_ErrorCode(struct soap*, const char*, int, const _basefaults__BaseFaultType_ErrorCode *, const char*);
SOAP_FMAC3 _basefaults__BaseFaultType_ErrorCode * SOAP_FMAC4 soap_get__basefaults__BaseFaultType_ErrorCode(struct soap*, _basefaults__BaseFaultType_ErrorCode *, const char*, const char*);
SOAP_FMAC3 _basefaults__BaseFaultType_ErrorCode * SOAP_FMAC4 soap_in__basefaults__BaseFaultType_ErrorCode(struct soap*, const char*, _basefaults__BaseFaultType_ErrorCode *, const char*);
SOAP_FMAC5 _basefaults__BaseFaultType_ErrorCode * SOAP_FMAC6 soap_new__basefaults__BaseFaultType_ErrorCode(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__basefaults__BaseFaultType_ErrorCode(struct soap*, _basefaults__BaseFaultType_ErrorCode*);
SOAP_FMAC3 _basefaults__BaseFaultType_ErrorCode * SOAP_FMAC4 soap_instantiate__basefaults__BaseFaultType_ErrorCode(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__basefaults__BaseFaultType_ErrorCode(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__FaultSubcodeValues_
#define SOAP_TYPE_xsd__FaultSubcodeValues_ (43)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__FaultSubcodeValues_(struct soap*, const char*, int, const xsd__FaultSubcodeValues_ *, const char*);
SOAP_FMAC3 xsd__FaultSubcodeValues_ * SOAP_FMAC4 soap_get_xsd__FaultSubcodeValues_(struct soap*, xsd__FaultSubcodeValues_ *, const char*, const char*);
SOAP_FMAC3 xsd__FaultSubcodeValues_ * SOAP_FMAC4 soap_in_xsd__FaultSubcodeValues_(struct soap*, const char*, xsd__FaultSubcodeValues_ *, const char*);
SOAP_FMAC5 xsd__FaultSubcodeValues_ * SOAP_FMAC6 soap_new_xsd__FaultSubcodeValues_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__FaultSubcodeValues_(struct soap*, xsd__FaultSubcodeValues_*);
SOAP_FMAC3 xsd__FaultSubcodeValues_ * SOAP_FMAC4 soap_instantiate_xsd__FaultSubcodeValues_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__FaultSubcodeValues_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__RelationshipTypeValues_
#define SOAP_TYPE_xsd__RelationshipTypeValues_ (41)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__RelationshipTypeValues_(struct soap*, const char*, int, const xsd__RelationshipTypeValues_ *, const char*);
SOAP_FMAC3 xsd__RelationshipTypeValues_ * SOAP_FMAC4 soap_get_xsd__RelationshipTypeValues_(struct soap*, xsd__RelationshipTypeValues_ *, const char*, const char*);
SOAP_FMAC3 xsd__RelationshipTypeValues_ * SOAP_FMAC4 soap_in_xsd__RelationshipTypeValues_(struct soap*, const char*, xsd__RelationshipTypeValues_ *, const char*);
SOAP_FMAC5 xsd__RelationshipTypeValues_ * SOAP_FMAC6 soap_new_xsd__RelationshipTypeValues_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__RelationshipTypeValues_(struct soap*, xsd__RelationshipTypeValues_*);
SOAP_FMAC3 xsd__RelationshipTypeValues_ * SOAP_FMAC4 soap_instantiate_xsd__RelationshipTypeValues_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__RelationshipTypeValues_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_basefaults__BaseFaultType
#define SOAP_TYPE_basefaults__BaseFaultType (39)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_basefaults__BaseFaultType(struct soap*, const char*, int, const basefaults__BaseFaultType *, const char*);
SOAP_FMAC3 basefaults__BaseFaultType * SOAP_FMAC4 soap_get_basefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType *, const char*, const char*);
SOAP_FMAC3 basefaults__BaseFaultType * SOAP_FMAC4 soap_in_basefaults__BaseFaultType(struct soap*, const char*, basefaults__BaseFaultType *, const char*);
SOAP_FMAC5 basefaults__BaseFaultType * SOAP_FMAC6 soap_new_basefaults__BaseFaultType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_basefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType*);
SOAP_FMAC3 basefaults__BaseFaultType * SOAP_FMAC4 soap_instantiate_basefaults__BaseFaultType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_basefaults__BaseFaultType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__AttributedURI
#define SOAP_TYPE_xsd__AttributedURI (38)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__AttributedURI(struct soap*, const char*, int, const xsd__AttributedURI *, const char*);
SOAP_FMAC3 xsd__AttributedURI * SOAP_FMAC4 soap_get_xsd__AttributedURI(struct soap*, xsd__AttributedURI *, const char*, const char*);
SOAP_FMAC3 xsd__AttributedURI * SOAP_FMAC4 soap_in_xsd__AttributedURI(struct soap*, const char*, xsd__AttributedURI *, const char*);
SOAP_FMAC5 xsd__AttributedURI * SOAP_FMAC6 soap_new_xsd__AttributedURI(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__AttributedURI(struct soap*, xsd__AttributedURI*);
SOAP_FMAC3 xsd__AttributedURI * SOAP_FMAC4 soap_instantiate_xsd__AttributedURI(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__AttributedURI(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__AttributedQName
#define SOAP_TYPE_xsd__AttributedQName (37)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__AttributedQName(struct soap*, const char*, int, const xsd__AttributedQName *, const char*);
SOAP_FMAC3 xsd__AttributedQName * SOAP_FMAC4 soap_get_xsd__AttributedQName(struct soap*, xsd__AttributedQName *, const char*, const char*);
SOAP_FMAC3 xsd__AttributedQName * SOAP_FMAC4 soap_in_xsd__AttributedQName(struct soap*, const char*, xsd__AttributedQName *, const char*);
SOAP_FMAC5 xsd__AttributedQName * SOAP_FMAC6 soap_new_xsd__AttributedQName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__AttributedQName(struct soap*, xsd__AttributedQName*);
SOAP_FMAC3 xsd__AttributedQName * SOAP_FMAC4 soap_instantiate_xsd__AttributedQName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__AttributedQName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__ReplyAfterType
#define SOAP_TYPE_xsd__ReplyAfterType (36)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__ReplyAfterType(struct soap*, const char*, int, const xsd__ReplyAfterType *, const char*);
SOAP_FMAC3 xsd__ReplyAfterType * SOAP_FMAC4 soap_get_xsd__ReplyAfterType(struct soap*, xsd__ReplyAfterType *, const char*, const char*);
SOAP_FMAC3 xsd__ReplyAfterType * SOAP_FMAC4 soap_in_xsd__ReplyAfterType(struct soap*, const char*, xsd__ReplyAfterType *, const char*);
SOAP_FMAC5 xsd__ReplyAfterType * SOAP_FMAC6 soap_new_xsd__ReplyAfterType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__ReplyAfterType(struct soap*, xsd__ReplyAfterType*);
SOAP_FMAC3 xsd__ReplyAfterType * SOAP_FMAC4 soap_instantiate_xsd__ReplyAfterType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__ReplyAfterType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__Relationship
#define SOAP_TYPE_xsd__Relationship (35)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__Relationship(struct soap*, const char*, int, const xsd__Relationship *, const char*);
SOAP_FMAC3 xsd__Relationship * SOAP_FMAC4 soap_get_xsd__Relationship(struct soap*, xsd__Relationship *, const char*, const char*);
SOAP_FMAC3 xsd__Relationship * SOAP_FMAC4 soap_in_xsd__Relationship(struct soap*, const char*, xsd__Relationship *, const char*);
SOAP_FMAC5 xsd__Relationship * SOAP_FMAC6 soap_new_xsd__Relationship(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__Relationship(struct soap*, xsd__Relationship*);
SOAP_FMAC3 xsd__Relationship * SOAP_FMAC4 soap_instantiate_xsd__Relationship(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__Relationship(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__ServiceNameType
#define SOAP_TYPE_xsd__ServiceNameType (34)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__ServiceNameType(struct soap*, const char*, int, const xsd__ServiceNameType *, const char*);
SOAP_FMAC3 xsd__ServiceNameType * SOAP_FMAC4 soap_get_xsd__ServiceNameType(struct soap*, xsd__ServiceNameType *, const char*, const char*);
SOAP_FMAC3 xsd__ServiceNameType * SOAP_FMAC4 soap_in_xsd__ServiceNameType(struct soap*, const char*, xsd__ServiceNameType *, const char*);
SOAP_FMAC5 xsd__ServiceNameType * SOAP_FMAC6 soap_new_xsd__ServiceNameType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__ServiceNameType(struct soap*, xsd__ServiceNameType*);
SOAP_FMAC3 xsd__ServiceNameType * SOAP_FMAC4 soap_instantiate_xsd__ServiceNameType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__ServiceNameType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__ReferencePropertiesType
#define SOAP_TYPE_xsd__ReferencePropertiesType (33)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__ReferencePropertiesType(struct soap*, const char*, int, const xsd__ReferencePropertiesType *, const char*);
SOAP_FMAC3 xsd__ReferencePropertiesType * SOAP_FMAC4 soap_get_xsd__ReferencePropertiesType(struct soap*, xsd__ReferencePropertiesType *, const char*, const char*);
SOAP_FMAC3 xsd__ReferencePropertiesType * SOAP_FMAC4 soap_in_xsd__ReferencePropertiesType(struct soap*, const char*, xsd__ReferencePropertiesType *, const char*);
SOAP_FMAC5 xsd__ReferencePropertiesType * SOAP_FMAC6 soap_new_xsd__ReferencePropertiesType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__ReferencePropertiesType(struct soap*, xsd__ReferencePropertiesType*);
SOAP_FMAC3 xsd__ReferencePropertiesType * SOAP_FMAC4 soap_instantiate_xsd__ReferencePropertiesType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__ReferencePropertiesType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__EndpointReferenceType
#define SOAP_TYPE_xsd__EndpointReferenceType (32)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__EndpointReferenceType(struct soap*, const char*, int, const xsd__EndpointReferenceType *, const char*);
SOAP_FMAC3 xsd__EndpointReferenceType * SOAP_FMAC4 soap_get_xsd__EndpointReferenceType(struct soap*, xsd__EndpointReferenceType *, const char*, const char*);
SOAP_FMAC3 xsd__EndpointReferenceType * SOAP_FMAC4 soap_in_xsd__EndpointReferenceType(struct soap*, const char*, xsd__EndpointReferenceType *, const char*);
SOAP_FMAC5 xsd__EndpointReferenceType * SOAP_FMAC6 soap_new_xsd__EndpointReferenceType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__EndpointReferenceType(struct soap*, xsd__EndpointReferenceType*);
SOAP_FMAC3 xsd__EndpointReferenceType * SOAP_FMAC4 soap_instantiate_xsd__EndpointReferenceType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__EndpointReferenceType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__lifetime__TerminationNotification
#define SOAP_TYPE__lifetime__TerminationNotification (31)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__lifetime__TerminationNotification(struct soap*, const char*, int, const _lifetime__TerminationNotification *, const char*);
SOAP_FMAC3 _lifetime__TerminationNotification * SOAP_FMAC4 soap_get__lifetime__TerminationNotification(struct soap*, _lifetime__TerminationNotification *, const char*, const char*);
SOAP_FMAC3 _lifetime__TerminationNotification * SOAP_FMAC4 soap_in__lifetime__TerminationNotification(struct soap*, const char*, _lifetime__TerminationNotification *, const char*);
SOAP_FMAC5 _lifetime__TerminationNotification * SOAP_FMAC6 soap_new__lifetime__TerminationNotification(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__lifetime__TerminationNotification(struct soap*, _lifetime__TerminationNotification*);
SOAP_FMAC3 _lifetime__TerminationNotification * SOAP_FMAC4 soap_instantiate__lifetime__TerminationNotification(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__lifetime__TerminationNotification(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__lifetime__SetTerminationTimeResponse
#define SOAP_TYPE__lifetime__SetTerminationTimeResponse (30)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__lifetime__SetTerminationTimeResponse(struct soap*, const char*, int, const _lifetime__SetTerminationTimeResponse *, const char*);
SOAP_FMAC3 _lifetime__SetTerminationTimeResponse * SOAP_FMAC4 soap_get__lifetime__SetTerminationTimeResponse(struct soap*, _lifetime__SetTerminationTimeResponse *, const char*, const char*);
SOAP_FMAC3 _lifetime__SetTerminationTimeResponse * SOAP_FMAC4 soap_in__lifetime__SetTerminationTimeResponse(struct soap*, const char*, _lifetime__SetTerminationTimeResponse *, const char*);
SOAP_FMAC5 _lifetime__SetTerminationTimeResponse * SOAP_FMAC6 soap_new__lifetime__SetTerminationTimeResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__lifetime__SetTerminationTimeResponse(struct soap*, _lifetime__SetTerminationTimeResponse*);
SOAP_FMAC3 _lifetime__SetTerminationTimeResponse * SOAP_FMAC4 soap_instantiate__lifetime__SetTerminationTimeResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__lifetime__SetTerminationTimeResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__lifetime__SetTerminationTime
#define SOAP_TYPE__lifetime__SetTerminationTime (29)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__lifetime__SetTerminationTime(struct soap*, const char*, int, const _lifetime__SetTerminationTime *, const char*);
SOAP_FMAC3 _lifetime__SetTerminationTime * SOAP_FMAC4 soap_get__lifetime__SetTerminationTime(struct soap*, _lifetime__SetTerminationTime *, const char*, const char*);
SOAP_FMAC3 _lifetime__SetTerminationTime * SOAP_FMAC4 soap_in__lifetime__SetTerminationTime(struct soap*, const char*, _lifetime__SetTerminationTime *, const char*);
SOAP_FMAC5 _lifetime__SetTerminationTime * SOAP_FMAC6 soap_new__lifetime__SetTerminationTime(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__lifetime__SetTerminationTime(struct soap*, _lifetime__SetTerminationTime*);
SOAP_FMAC3 _lifetime__SetTerminationTime * SOAP_FMAC4 soap_instantiate__lifetime__SetTerminationTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__lifetime__SetTerminationTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__lifetime__DestroyResponse
#define SOAP_TYPE__lifetime__DestroyResponse (28)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__lifetime__DestroyResponse(struct soap*, const char*, int, const _lifetime__DestroyResponse *, const char*);
SOAP_FMAC3 _lifetime__DestroyResponse * SOAP_FMAC4 soap_get__lifetime__DestroyResponse(struct soap*, _lifetime__DestroyResponse *, const char*, const char*);
SOAP_FMAC3 _lifetime__DestroyResponse * SOAP_FMAC4 soap_in__lifetime__DestroyResponse(struct soap*, const char*, _lifetime__DestroyResponse *, const char*);
SOAP_FMAC5 _lifetime__DestroyResponse * SOAP_FMAC6 soap_new__lifetime__DestroyResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__lifetime__DestroyResponse(struct soap*, _lifetime__DestroyResponse*);
SOAP_FMAC3 _lifetime__DestroyResponse * SOAP_FMAC4 soap_instantiate__lifetime__DestroyResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__lifetime__DestroyResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__lifetime__Destroy
#define SOAP_TYPE__lifetime__Destroy (27)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__lifetime__Destroy(struct soap*, const char*, int, const _lifetime__Destroy *, const char*);
SOAP_FMAC3 _lifetime__Destroy * SOAP_FMAC4 soap_get__lifetime__Destroy(struct soap*, _lifetime__Destroy *, const char*, const char*);
SOAP_FMAC3 _lifetime__Destroy * SOAP_FMAC4 soap_in__lifetime__Destroy(struct soap*, const char*, _lifetime__Destroy *, const char*);
SOAP_FMAC5 _lifetime__Destroy * SOAP_FMAC6 soap_new__lifetime__Destroy(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__lifetime__Destroy(struct soap*, _lifetime__Destroy*);
SOAP_FMAC3 _lifetime__Destroy * SOAP_FMAC4 soap_instantiate__lifetime__Destroy(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__lifetime__Destroy(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE__lifetime__ScheduledResourceTerminationRP
#define SOAP_TYPE__lifetime__ScheduledResourceTerminationRP (26)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out__lifetime__ScheduledResourceTerminationRP(struct soap*, const char*, int, const _lifetime__ScheduledResourceTerminationRP *, const char*);
SOAP_FMAC3 _lifetime__ScheduledResourceTerminationRP * SOAP_FMAC4 soap_get__lifetime__ScheduledResourceTerminationRP(struct soap*, _lifetime__ScheduledResourceTerminationRP *, const char*, const char*);
SOAP_FMAC3 _lifetime__ScheduledResourceTerminationRP * SOAP_FMAC4 soap_in__lifetime__ScheduledResourceTerminationRP(struct soap*, const char*, _lifetime__ScheduledResourceTerminationRP *, const char*);
SOAP_FMAC5 _lifetime__ScheduledResourceTerminationRP * SOAP_FMAC6 soap_new__lifetime__ScheduledResourceTerminationRP(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete__lifetime__ScheduledResourceTerminationRP(struct soap*, _lifetime__ScheduledResourceTerminationRP*);
SOAP_FMAC3 _lifetime__ScheduledResourceTerminationRP * SOAP_FMAC4 soap_instantiate__lifetime__ScheduledResourceTerminationRP(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy__lifetime__ScheduledResourceTerminationRP(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_lifetime__TerminationTimeChangeRejectedFaultType
#define SOAP_TYPE_lifetime__TerminationTimeChangeRejectedFaultType (25)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_lifetime__TerminationTimeChangeRejectedFaultType(struct soap*, const char*, int, const lifetime__TerminationTimeChangeRejectedFaultType *, const char*);
SOAP_FMAC3 lifetime__TerminationTimeChangeRejectedFaultType * SOAP_FMAC4 soap_get_lifetime__TerminationTimeChangeRejectedFaultType(struct soap*, lifetime__TerminationTimeChangeRejectedFaultType *, const char*, const char*);
SOAP_FMAC3 lifetime__TerminationTimeChangeRejectedFaultType * SOAP_FMAC4 soap_in_lifetime__TerminationTimeChangeRejectedFaultType(struct soap*, const char*, lifetime__TerminationTimeChangeRejectedFaultType *, const char*);
SOAP_FMAC5 lifetime__TerminationTimeChangeRejectedFaultType * SOAP_FMAC6 soap_new_lifetime__TerminationTimeChangeRejectedFaultType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_lifetime__TerminationTimeChangeRejectedFaultType(struct soap*, lifetime__TerminationTimeChangeRejectedFaultType*);
SOAP_FMAC3 lifetime__TerminationTimeChangeRejectedFaultType * SOAP_FMAC4 soap_instantiate_lifetime__TerminationTimeChangeRejectedFaultType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_lifetime__TerminationTimeChangeRejectedFaultType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_lifetime__UnableToSetTerminationTimeFaultType
#define SOAP_TYPE_lifetime__UnableToSetTerminationTimeFaultType (24)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_lifetime__UnableToSetTerminationTimeFaultType(struct soap*, const char*, int, const lifetime__UnableToSetTerminationTimeFaultType *, const char*);
SOAP_FMAC3 lifetime__UnableToSetTerminationTimeFaultType * SOAP_FMAC4 soap_get_lifetime__UnableToSetTerminationTimeFaultType(struct soap*, lifetime__UnableToSetTerminationTimeFaultType *, const char*, const char*);
SOAP_FMAC3 lifetime__UnableToSetTerminationTimeFaultType * SOAP_FMAC4 soap_in_lifetime__UnableToSetTerminationTimeFaultType(struct soap*, const char*, lifetime__UnableToSetTerminationTimeFaultType *, const char*);
SOAP_FMAC5 lifetime__UnableToSetTerminationTimeFaultType * SOAP_FMAC6 soap_new_lifetime__UnableToSetTerminationTimeFaultType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_lifetime__UnableToSetTerminationTimeFaultType(struct soap*, lifetime__UnableToSetTerminationTimeFaultType*);
SOAP_FMAC3 lifetime__UnableToSetTerminationTimeFaultType * SOAP_FMAC4 soap_instantiate_lifetime__UnableToSetTerminationTimeFaultType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_lifetime__UnableToSetTerminationTimeFaultType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_lifetime__ResourceNotDestroyedFaultType
#define SOAP_TYPE_lifetime__ResourceNotDestroyedFaultType (23)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_lifetime__ResourceNotDestroyedFaultType(struct soap*, const char*, int, const lifetime__ResourceNotDestroyedFaultType *, const char*);
SOAP_FMAC3 lifetime__ResourceNotDestroyedFaultType * SOAP_FMAC4 soap_get_lifetime__ResourceNotDestroyedFaultType(struct soap*, lifetime__ResourceNotDestroyedFaultType *, const char*, const char*);
SOAP_FMAC3 lifetime__ResourceNotDestroyedFaultType * SOAP_FMAC4 soap_in_lifetime__ResourceNotDestroyedFaultType(struct soap*, const char*, lifetime__ResourceNotDestroyedFaultType *, const char*);
SOAP_FMAC5 lifetime__ResourceNotDestroyedFaultType * SOAP_FMAC6 soap_new_lifetime__ResourceNotDestroyedFaultType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_lifetime__ResourceNotDestroyedFaultType(struct soap*, lifetime__ResourceNotDestroyedFaultType*);
SOAP_FMAC3 lifetime__ResourceNotDestroyedFaultType * SOAP_FMAC4 soap_instantiate_lifetime__ResourceNotDestroyedFaultType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_lifetime__ResourceNotDestroyedFaultType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_lifetime__ResourceUnknownFaultType
#define SOAP_TYPE_lifetime__ResourceUnknownFaultType (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_lifetime__ResourceUnknownFaultType(struct soap*, const char*, int, const lifetime__ResourceUnknownFaultType *, const char*);
SOAP_FMAC3 lifetime__ResourceUnknownFaultType * SOAP_FMAC4 soap_get_lifetime__ResourceUnknownFaultType(struct soap*, lifetime__ResourceUnknownFaultType *, const char*, const char*);
SOAP_FMAC3 lifetime__ResourceUnknownFaultType * SOAP_FMAC4 soap_in_lifetime__ResourceUnknownFaultType(struct soap*, const char*, lifetime__ResourceUnknownFaultType *, const char*);
SOAP_FMAC5 lifetime__ResourceUnknownFaultType * SOAP_FMAC6 soap_new_lifetime__ResourceUnknownFaultType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_lifetime__ResourceUnknownFaultType(struct soap*, lifetime__ResourceUnknownFaultType*);
SOAP_FMAC3 lifetime__ResourceUnknownFaultType * SOAP_FMAC4 soap_instantiate_lifetime__ResourceUnknownFaultType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_lifetime__ResourceUnknownFaultType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, const xsd__string *, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_get_xsd__string(struct soap*, xsd__string *, const char*, const char*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, xsd__string *, const char*);
SOAP_FMAC5 xsd__string * SOAP_FMAC6 soap_new_xsd__string(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__string(struct soap*, xsd__string*);
SOAP_FMAC3 xsd__string * SOAP_FMAC4 soap_instantiate_xsd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__nonNegativeInteger_
#define SOAP_TYPE_xsd__nonNegativeInteger_ (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonNegativeInteger_(struct soap*, const char*, int, const xsd__nonNegativeInteger_ *, const char*);
SOAP_FMAC3 xsd__nonNegativeInteger_ * SOAP_FMAC4 soap_get_xsd__nonNegativeInteger_(struct soap*, xsd__nonNegativeInteger_ *, const char*, const char*);
SOAP_FMAC3 xsd__nonNegativeInteger_ * SOAP_FMAC4 soap_in_xsd__nonNegativeInteger_(struct soap*, const char*, xsd__nonNegativeInteger_ *, const char*);
SOAP_FMAC5 xsd__nonNegativeInteger_ * SOAP_FMAC6 soap_new_xsd__nonNegativeInteger_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__nonNegativeInteger_(struct soap*, xsd__nonNegativeInteger_*);
SOAP_FMAC3 xsd__nonNegativeInteger_ * SOAP_FMAC4 soap_instantiate_xsd__nonNegativeInteger_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__nonNegativeInteger_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime(struct soap*, const char*, int, const xsd__dateTime *, const char*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_get_xsd__dateTime(struct soap*, xsd__dateTime *, const char*, const char*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_in_xsd__dateTime(struct soap*, const char*, xsd__dateTime *, const char*);
SOAP_FMAC5 xsd__dateTime * SOAP_FMAC6 soap_new_xsd__dateTime(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__dateTime(struct soap*, xsd__dateTime*);
SOAP_FMAC3 xsd__dateTime * SOAP_FMAC4 soap_instantiate_xsd__dateTime(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__dateTime(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const xsd__boolean *, const char*);
SOAP_FMAC3 xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, xsd__boolean *, const char*, const char*);
SOAP_FMAC3 xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, xsd__boolean *, const char*);
SOAP_FMAC5 xsd__boolean * SOAP_FMAC6 soap_new_xsd__boolean(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__boolean(struct soap*, xsd__boolean*);
SOAP_FMAC3 xsd__boolean * SOAP_FMAC4 soap_instantiate_xsd__boolean(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__boolean(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyURI_
#define SOAP_TYPE_xsd__anyURI_ (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI_(struct soap*, const char*, int, const xsd__anyURI_ *, const char*);
SOAP_FMAC3 xsd__anyURI_ * SOAP_FMAC4 soap_get_xsd__anyURI_(struct soap*, xsd__anyURI_ *, const char*, const char*);
SOAP_FMAC3 xsd__anyURI_ * SOAP_FMAC4 soap_in_xsd__anyURI_(struct soap*, const char*, xsd__anyURI_ *, const char*);
SOAP_FMAC5 xsd__anyURI_ * SOAP_FMAC6 soap_new_xsd__anyURI_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyURI_(struct soap*, xsd__anyURI_*);
SOAP_FMAC3 xsd__anyURI_ * SOAP_FMAC4 soap_instantiate_xsd__anyURI_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyURI_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__QName
#define SOAP_TYPE_xsd__QName (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__QName(struct soap*, const char*, int, const xsd__QName *, const char*);
SOAP_FMAC3 xsd__QName * SOAP_FMAC4 soap_get_xsd__QName(struct soap*, xsd__QName *, const char*, const char*);
SOAP_FMAC3 xsd__QName * SOAP_FMAC4 soap_in_xsd__QName(struct soap*, const char*, xsd__QName *, const char*);
SOAP_FMAC5 xsd__QName * SOAP_FMAC6 soap_new_xsd__QName(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__QName(struct soap*, xsd__QName*);
SOAP_FMAC3 xsd__QName * SOAP_FMAC4 soap_instantiate_xsd__QName(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__QName(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__NCName_
#define SOAP_TYPE_xsd__NCName_ (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__NCName_(struct soap*, const char*, int, const xsd__NCName_ *, const char*);
SOAP_FMAC3 xsd__NCName_ * SOAP_FMAC4 soap_get_xsd__NCName_(struct soap*, xsd__NCName_ *, const char*, const char*);
SOAP_FMAC3 xsd__NCName_ * SOAP_FMAC4 soap_in_xsd__NCName_(struct soap*, const char*, xsd__NCName_ *, const char*);
SOAP_FMAC5 xsd__NCName_ * SOAP_FMAC6 soap_new_xsd__NCName_(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__NCName_(struct soap*, xsd__NCName_*);
SOAP_FMAC3 xsd__NCName_ * SOAP_FMAC4 soap_instantiate_xsd__NCName_(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__NCName_(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__anyType
#define SOAP_TYPE_xsd__anyType (6)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyType(struct soap*, const char*, int, const xsd__anyType *, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_get_xsd__anyType(struct soap*, xsd__anyType *, const char*, const char*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_in_xsd__anyType(struct soap*, const char*, xsd__anyType *, const char*);
SOAP_FMAC5 xsd__anyType * SOAP_FMAC6 soap_new_xsd__anyType(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__anyType(struct soap*, xsd__anyType*);
SOAP_FMAC3 xsd__anyType * SOAP_FMAC4 soap_instantiate_xsd__anyType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__anyType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___migol__Destroy
#define SOAP_TYPE___migol__Destroy (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___migol__Destroy(struct soap*, struct __migol__Destroy *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___migol__Destroy(struct soap*, const struct __migol__Destroy *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___migol__Destroy(struct soap*, const struct __migol__Destroy *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___migol__Destroy(struct soap*, const char*, int, const struct __migol__Destroy *, const char*);
SOAP_FMAC3 struct __migol__Destroy * SOAP_FMAC4 soap_get___migol__Destroy(struct soap*, struct __migol__Destroy *, const char*, const char*);
SOAP_FMAC3 struct __migol__Destroy * SOAP_FMAC4 soap_in___migol__Destroy(struct soap*, const char*, struct __migol__Destroy *, const char*);
SOAP_FMAC5 struct __migol__Destroy * SOAP_FMAC6 soap_new___migol__Destroy(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___migol__Destroy(struct soap*, struct __migol__Destroy*);
SOAP_FMAC3 struct __migol__Destroy * SOAP_FMAC4 soap_instantiate___migol__Destroy(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___migol__Destroy(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___migol__checkPoint
#define SOAP_TYPE___migol__checkPoint (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___migol__checkPoint(struct soap*, struct __migol__checkPoint *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___migol__checkPoint(struct soap*, const struct __migol__checkPoint *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___migol__checkPoint(struct soap*, const struct __migol__checkPoint *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___migol__checkPoint(struct soap*, const char*, int, const struct __migol__checkPoint *, const char*);
SOAP_FMAC3 struct __migol__checkPoint * SOAP_FMAC4 soap_get___migol__checkPoint(struct soap*, struct __migol__checkPoint *, const char*, const char*);
SOAP_FMAC3 struct __migol__checkPoint * SOAP_FMAC4 soap_in___migol__checkPoint(struct soap*, const char*, struct __migol__checkPoint *, const char*);
SOAP_FMAC5 struct __migol__checkPoint * SOAP_FMAC6 soap_new___migol__checkPoint(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___migol__checkPoint(struct soap*, struct __migol__checkPoint*);
SOAP_FMAC3 struct __migol__checkPoint * SOAP_FMAC4 soap_instantiate___migol__checkPoint(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___migol__checkPoint(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___migol__checkPointResponse
#define SOAP_TYPE___migol__checkPointResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___migol__checkPointResponse(struct soap*, struct __migol__checkPointResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___migol__checkPointResponse(struct soap*, const struct __migol__checkPointResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___migol__checkPointResponse(struct soap*, const struct __migol__checkPointResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___migol__checkPointResponse(struct soap*, const char*, int, const struct __migol__checkPointResponse *, const char*);
SOAP_FMAC3 struct __migol__checkPointResponse * SOAP_FMAC4 soap_get___migol__checkPointResponse(struct soap*, struct __migol__checkPointResponse *, const char*, const char*);
SOAP_FMAC3 struct __migol__checkPointResponse * SOAP_FMAC4 soap_in___migol__checkPointResponse(struct soap*, const char*, struct __migol__checkPointResponse *, const char*);
SOAP_FMAC5 struct __migol__checkPointResponse * SOAP_FMAC6 soap_new___migol__checkPointResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___migol__checkPointResponse(struct soap*, struct __migol__checkPointResponse*);
SOAP_FMAC3 struct __migol__checkPointResponse * SOAP_FMAC4 soap_instantiate___migol__checkPointResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___migol__checkPointResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___migol__checkService
#define SOAP_TYPE___migol__checkService (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___migol__checkService(struct soap*, struct __migol__checkService *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___migol__checkService(struct soap*, const struct __migol__checkService *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___migol__checkService(struct soap*, const struct __migol__checkService *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___migol__checkService(struct soap*, const char*, int, const struct __migol__checkService *, const char*);
SOAP_FMAC3 struct __migol__checkService * SOAP_FMAC4 soap_get___migol__checkService(struct soap*, struct __migol__checkService *, const char*, const char*);
SOAP_FMAC3 struct __migol__checkService * SOAP_FMAC4 soap_in___migol__checkService(struct soap*, const char*, struct __migol__checkService *, const char*);
SOAP_FMAC5 struct __migol__checkService * SOAP_FMAC6 soap_new___migol__checkService(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___migol__checkService(struct soap*, struct __migol__checkService*);
SOAP_FMAC3 struct __migol__checkService * SOAP_FMAC4 soap_instantiate___migol__checkService(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___migol__checkService(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___migol__checkServiceResponse
#define SOAP_TYPE___migol__checkServiceResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___migol__checkServiceResponse(struct soap*, struct __migol__checkServiceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___migol__checkServiceResponse(struct soap*, const struct __migol__checkServiceResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put___migol__checkServiceResponse(struct soap*, const struct __migol__checkServiceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___migol__checkServiceResponse(struct soap*, const char*, int, const struct __migol__checkServiceResponse *, const char*);
SOAP_FMAC3 struct __migol__checkServiceResponse * SOAP_FMAC4 soap_get___migol__checkServiceResponse(struct soap*, struct __migol__checkServiceResponse *, const char*, const char*);
SOAP_FMAC3 struct __migol__checkServiceResponse * SOAP_FMAC4 soap_in___migol__checkServiceResponse(struct soap*, const char*, struct __migol__checkServiceResponse *, const char*);
SOAP_FMAC5 struct __migol__checkServiceResponse * SOAP_FMAC6 soap_new___migol__checkServiceResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete___migol__checkServiceResponse(struct soap*, struct __migol__checkServiceResponse*);
SOAP_FMAC3 struct __migol__checkServiceResponse * SOAP_FMAC4 soap_instantiate___migol__checkServiceResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___migol__checkServiceResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTo_lifetime__DestroyResponse
#define SOAP_TYPE_PointerTo_lifetime__DestroyResponse (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_lifetime__DestroyResponse(struct soap*, _lifetime__DestroyResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_lifetime__DestroyResponse(struct soap*, _lifetime__DestroyResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_lifetime__DestroyResponse(struct soap*, const char *, int, _lifetime__DestroyResponse *const*, const char *);
SOAP_FMAC3 _lifetime__DestroyResponse ** SOAP_FMAC4 soap_get_PointerTo_lifetime__DestroyResponse(struct soap*, _lifetime__DestroyResponse **, const char*, const char*);
SOAP_FMAC3 _lifetime__DestroyResponse ** SOAP_FMAC4 soap_in_PointerTo_lifetime__DestroyResponse(struct soap*, const char*, _lifetime__DestroyResponse **, const char*);

#ifndef SOAP_TYPE_PointerTo_lifetime__Destroy
#define SOAP_TYPE_PointerTo_lifetime__Destroy (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_lifetime__Destroy(struct soap*, _lifetime__Destroy *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_lifetime__Destroy(struct soap*, _lifetime__Destroy *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_lifetime__Destroy(struct soap*, const char *, int, _lifetime__Destroy *const*, const char *);
SOAP_FMAC3 _lifetime__Destroy ** SOAP_FMAC4 soap_get_PointerTo_lifetime__Destroy(struct soap*, _lifetime__Destroy **, const char*, const char*);
SOAP_FMAC3 _lifetime__Destroy ** SOAP_FMAC4 soap_in_PointerTo_lifetime__Destroy(struct soap*, const char*, _lifetime__Destroy **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTobasefaults__BaseFaultType
#define SOAP_TYPE_PointerToPointerTobasefaults__BaseFaultType (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTobasefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTobasefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTobasefaults__BaseFaultType(struct soap*, const char *, int, basefaults__BaseFaultType **const*, const char *);
SOAP_FMAC3 basefaults__BaseFaultType *** SOAP_FMAC4 soap_get_PointerToPointerTobasefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType ***, const char*, const char*);
SOAP_FMAC3 basefaults__BaseFaultType *** SOAP_FMAC4 soap_in_PointerToPointerTobasefaults__BaseFaultType(struct soap*, const char*, basefaults__BaseFaultType ***, const char*);

#ifndef SOAP_TYPE_PointerTobasefaults__BaseFaultType
#define SOAP_TYPE_PointerTobasefaults__BaseFaultType (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTobasefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTobasefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTobasefaults__BaseFaultType(struct soap*, const char *, int, basefaults__BaseFaultType *const*, const char *);
SOAP_FMAC3 basefaults__BaseFaultType ** SOAP_FMAC4 soap_get_PointerTobasefaults__BaseFaultType(struct soap*, basefaults__BaseFaultType **, const char*, const char*);
SOAP_FMAC3 basefaults__BaseFaultType ** SOAP_FMAC4 soap_in_PointerTobasefaults__BaseFaultType(struct soap*, const char*, basefaults__BaseFaultType **, const char*);

#ifndef SOAP_TYPE_PointerTo_basefaults__BaseFaultType_Description
#define SOAP_TYPE_PointerTo_basefaults__BaseFaultType_Description (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_basefaults__BaseFaultType_Description(struct soap*, _basefaults__BaseFaultType_Description *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_basefaults__BaseFaultType_Description(struct soap*, _basefaults__BaseFaultType_Description *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_basefaults__BaseFaultType_Description(struct soap*, const char *, int, _basefaults__BaseFaultType_Description *const*, const char *);
SOAP_FMAC3 _basefaults__BaseFaultType_Description ** SOAP_FMAC4 soap_get_PointerTo_basefaults__BaseFaultType_Description(struct soap*, _basefaults__BaseFaultType_Description **, const char*, const char*);
SOAP_FMAC3 _basefaults__BaseFaultType_Description ** SOAP_FMAC4 soap_in_PointerTo_basefaults__BaseFaultType_Description(struct soap*, const char*, _basefaults__BaseFaultType_Description **, const char*);

#ifndef SOAP_TYPE_PointerTo_basefaults__BaseFaultType_ErrorCode
#define SOAP_TYPE_PointerTo_basefaults__BaseFaultType_ErrorCode (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTo_basefaults__BaseFaultType_ErrorCode(struct soap*, _basefaults__BaseFaultType_ErrorCode *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTo_basefaults__BaseFaultType_ErrorCode(struct soap*, _basefaults__BaseFaultType_ErrorCode *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTo_basefaults__BaseFaultType_ErrorCode(struct soap*, const char *, int, _basefaults__BaseFaultType_ErrorCode *const*, const char *);
SOAP_FMAC3 _basefaults__BaseFaultType_ErrorCode ** SOAP_FMAC4 soap_get_PointerTo_basefaults__BaseFaultType_ErrorCode(struct soap*, _basefaults__BaseFaultType_ErrorCode **, const char*, const char*);
SOAP_FMAC3 _basefaults__BaseFaultType_ErrorCode ** SOAP_FMAC4 soap_in_PointerTo_basefaults__BaseFaultType_ErrorCode(struct soap*, const char*, _basefaults__BaseFaultType_ErrorCode **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__EndpointReferenceType
#define SOAP_TYPE_PointerToxsd__EndpointReferenceType (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__EndpointReferenceType(struct soap*, xsd__EndpointReferenceType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__EndpointReferenceType(struct soap*, xsd__EndpointReferenceType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__EndpointReferenceType(struct soap*, const char *, int, xsd__EndpointReferenceType *const*, const char *);
SOAP_FMAC3 xsd__EndpointReferenceType ** SOAP_FMAC4 soap_get_PointerToxsd__EndpointReferenceType(struct soap*, xsd__EndpointReferenceType **, const char*, const char*);
SOAP_FMAC3 xsd__EndpointReferenceType ** SOAP_FMAC4 soap_in_PointerToxsd__EndpointReferenceType(struct soap*, const char*, xsd__EndpointReferenceType **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__ServiceNameType
#define SOAP_TYPE_PointerToxsd__ServiceNameType (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__ServiceNameType(struct soap*, xsd__ServiceNameType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__ServiceNameType(struct soap*, xsd__ServiceNameType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__ServiceNameType(struct soap*, const char *, int, xsd__ServiceNameType *const*, const char *);
SOAP_FMAC3 xsd__ServiceNameType ** SOAP_FMAC4 soap_get_PointerToxsd__ServiceNameType(struct soap*, xsd__ServiceNameType **, const char*, const char*);
SOAP_FMAC3 xsd__ServiceNameType ** SOAP_FMAC4 soap_in_PointerToxsd__ServiceNameType(struct soap*, const char*, xsd__ServiceNameType **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__AttributedQName
#define SOAP_TYPE_PointerToxsd__AttributedQName (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__AttributedQName(struct soap*, xsd__AttributedQName *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__AttributedQName(struct soap*, xsd__AttributedQName *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__AttributedQName(struct soap*, const char *, int, xsd__AttributedQName *const*, const char *);
SOAP_FMAC3 xsd__AttributedQName ** SOAP_FMAC4 soap_get_PointerToxsd__AttributedQName(struct soap*, xsd__AttributedQName **, const char*, const char*);
SOAP_FMAC3 xsd__AttributedQName ** SOAP_FMAC4 soap_in_PointerToxsd__AttributedQName(struct soap*, const char*, xsd__AttributedQName **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__ReferencePropertiesType
#define SOAP_TYPE_PointerToxsd__ReferencePropertiesType (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__ReferencePropertiesType(struct soap*, xsd__ReferencePropertiesType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__ReferencePropertiesType(struct soap*, xsd__ReferencePropertiesType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__ReferencePropertiesType(struct soap*, const char *, int, xsd__ReferencePropertiesType *const*, const char *);
SOAP_FMAC3 xsd__ReferencePropertiesType ** SOAP_FMAC4 soap_get_PointerToxsd__ReferencePropertiesType(struct soap*, xsd__ReferencePropertiesType **, const char*, const char*);
SOAP_FMAC3 xsd__ReferencePropertiesType ** SOAP_FMAC4 soap_in_PointerToxsd__ReferencePropertiesType(struct soap*, const char*, xsd__ReferencePropertiesType **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__AttributedURI
#define SOAP_TYPE_PointerToxsd__AttributedURI (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__AttributedURI(struct soap*, xsd__AttributedURI *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__AttributedURI(struct soap*, xsd__AttributedURI *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__AttributedURI(struct soap*, const char *, int, xsd__AttributedURI *const*, const char *);
SOAP_FMAC3 xsd__AttributedURI ** SOAP_FMAC4 soap_get_PointerToxsd__AttributedURI(struct soap*, xsd__AttributedURI **, const char*, const char*);
SOAP_FMAC3 xsd__AttributedURI ** SOAP_FMAC4 soap_in_PointerToxsd__AttributedURI(struct soap*, const char*, xsd__AttributedURI **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__anyType
#define SOAP_TYPE_PointerToxsd__anyType (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__anyType(struct soap*, xsd__anyType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__anyType(struct soap*, xsd__anyType *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__anyType(struct soap*, const char *, int, xsd__anyType *const*, const char *);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_get_PointerToxsd__anyType(struct soap*, xsd__anyType **, const char*, const char*);
SOAP_FMAC3 xsd__anyType ** SOAP_FMAC4 soap_in_PointerToxsd__anyType(struct soap*, const char*, xsd__anyType **, const char*);

#ifndef SOAP_TYPE_PointerTotime
#define SOAP_TYPE_PointerTotime (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTotime(struct soap*, time_t *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTotime(struct soap*, time_t *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTotime(struct soap*, const char *, int, time_t *const*, const char *);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_get_PointerTotime(struct soap*, time_t **, const char*, const char*);
SOAP_FMAC3 time_t ** SOAP_FMAC4 soap_in_PointerTotime(struct soap*, const char*, time_t **, const char*);

#ifndef SOAP_TYPE__xml__lang
#define SOAP_TYPE__xml__lang (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__xml__lang(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__xml__lang(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__xml__lang(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__xml__lang(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__xml__lang(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__xml__lang(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__nonNegativeInteger
#define SOAP_TYPE_xsd__nonNegativeInteger (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__nonNegativeInteger(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__nonNegativeInteger(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__nonNegativeInteger(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__nonNegativeInteger(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__nonNegativeInteger(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__nonNegativeInteger(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__anyURI
#define SOAP_TYPE_xsd__anyURI (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__anyURI(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__anyURI(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__anyURI(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__anyURI(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__anyURI(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__anyURI(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__NCName
#define SOAP_TYPE_xsd__NCName (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__NCName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__NCName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__NCName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__NCName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__NCName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__NCName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#endif

/* End of monitorH.h */
