import os

SAGA_INCLUDE = os.environ['SAGA_LOCATION'] + '/include/'
SAGA_LIB = os.environ['SAGA_LOCATION'] + '/lib/'

env = Environment(
        CCFLAGS = "-g -O2 -Wall",
        CPPPATH = ['#source', '#source/utils', '#source/mapreduce',
            '#external/factory/', '#external/boost-log', SAGA_INCLUDE],
        LIBPATH = ['#source/mapreduce/',
            '#external/boost-log/libs/log/src/', SAGA_LIB],
        LIBS = ['protobuf'])

SConscript([
    'source/SConscript',
    'external/boost-log/libs/log/src/SConscript',
    'examples/wordcount/SConscript'
], exports = ['env'])
