#!/bin/sh
#
#PBS -A cct_dpg2_2007n
#PBS -q checkpt
#PBS -M jhkim@cct.lsu.edu
# Change ppn to 8 if running on Queen Bee
#PBS -l nodes=32:ppn=4
#PBS -l walltime=48:00:00
#PBS -V
#PBS -o NAMD_test.out
#PBS -e NAMD_test.err
#PBS -N namdrun1
export EXEC=namd2
export EXEC_DIR=/usr/local/packages/namd-2.6-mvapich-1.0-intel10.1
#export WORKDIR=$PBS_O_WORKDIR
export NPROCS=`wc -l $PBS_NODEFILE |gawk '//{print $1}'`
export CONV_RSH=ssh
export WORKDIR=/work/kimjh/SBOX/const_j1/run
cd $WORKDIR
mpirun -machinefile $PBS_NODEFILE -np $NPROCS $EXEC_DIR/$EXEC NPT.conf > namd.log

