#! /bin/csh
set KEY_CHECK="-o StrictHostKeyChecking=no"
cd ..; tar -cf GridNPB3.0.tar GridNPB3.0; cd GridNPB3.0
#setenv REMHOST1 turing
#setenv REMDIR1 /u/.realmounts/lc/frumkin/java/
#scp ../GridNPB3.0.tar ${REMHOST1}:${REMDIR1}/GridNPB3.0.tar
#rsh -f ${REMHOST1} "cd ${REMDIR1}; tar -xf GridNPB3.0.tar;\
#		 cd ${REMDIR1}/GridNPB3.0/scr;\
#		setenv CLASSPATH ${REMDIR1}/GridNPB3.0;\
#		./restartserv.sh &;"
#setenv REMHOST2 ranma
#setenv REMDIR2 /u/wk/frumkin/java/
#scp ../GridNPB3.0.tar ${REMHOST2}:${REMDIR2}/GridNPB3.0.tar
#rsh -f ${REMHOST2} "cd ${REMDIR2}; tar -xf GridNPB3.0.tar;\
#		cd ${REMDIR2}/GridNPB3.0/scr;\
#	       setenv CLASSPATH ${REMDIR2}/GridNPB3.0;\
#	       ./restartserv.sh &;"
setenv REMHOST1 wijngaar@192.220.101.22
setenv REMDIR1 /usr/home/wijngaar/java
scp $KEY_CHECK ../GridNPB3.0.tar ${REMHOST1}:${REMDIR1}/GridNPB3.0.tar
ssh $KEY_CHECK -f ${REMHOST1} "cd ${REMDIR1}; tar -xf GridNPB3.0.tar;\
		 cd ${REMDIR1}/GridNPB3.0/scr;\
		setenv CLASSPATH ${REMDIR1}/GridNPB3.0;\
		./restartserv.sh &;"
