#!/bin/sh

if [ -z "$SAGA_LOCATION" ]
then
	echo "Please set your SAGA_LOCATION variable, or else it aint gonna work...
fi

#Add the Jython jar. Ubuntu puts it (if installed) in /usr/share/java
#Or you specify yourself in JYTHON_JAR...
A_JAR="/usr/share/java/jython.jar"
if [ -e "$A_JAR" ]   
then
  if [ -z "$JYTHON_JAR"]
    then
       JYTHON_JAR="/usr/share/java/jython.jar"
  fi
fi

#Specify where Jython can find the Jysaga *.py files. If you run 
#this script from test/, the files are in "../src" , else you specify
#them yourself in $JYSAGA
if [ -z "$JYSAGA" ] 
then
  PPATH="../src"
else
  PPATH="$JYSAGA"
fi

#Specify where Jython can find the Jython library files. Ubuntu puts
#them (if installed) in /usr/lib/site-python. Else you specify
#them yourself in $JYTHON_HOME
if [ -e "/usr/lib/site-python" ]
then 
  PPATH=$PPATH:"/usr/lib/site-python"
fi  

if [ ! -z "$JYTHON_HOME" ]
then
  PPATH=$PPATH:$JYTHON_HOME
fi

java \
  -cp $SAGA_LOCATION/lib/log4j-1.2.13.jar:$SAGA_LOCATION/lib/saga-api-1.0.jar:$SAGA_LOCATION/lib/saga-impl-1.0.jar:$JYTHON_JAR \
  -Dlog4j.configuration=file:$SAGA_LOCATION/log4j.properties \
  -Djava.endorsed.dirs=$SAGA_LOCATION/lib/adaptors/GridsamAdaptor/endorsed \
  -Dpython.path=$PPATH \
  'org.python.util.jython' "$@"
  
  